project:
  type: website
  output-dir: docs
website:
   
   page-footer: 
     left: "Data Science for the Public Good" 
   navbar: 
      title: "AI Housing Homepage"
      background: "#969696"
        
format:
  html:
    embed-resources: true
    theme: lux
    
    backgroundcolor: "#9ecae1"



